---
title: "Projects"
---

## Project 1

### Dubai Property Pricing Analysis  
This project investigates how property characteristics such as size, number of bedrooms, bathrooms, and location affect real estate prices in Dubai. Using a dataset of over 1,800 properties, I conducted data cleaning, exploratory analysis, and multiple regression modeling to identify key pricing predictors. The project demonstrates how regression analysis can be applied in real estate business contexts and highlights how structural features and location-driven attributes influence market value..


🔗 **Project Link:**  
[📄 Dubai Property Pricing Analysis (PDF)](https://github.com/MercyOgbede-chi/Exploratory-Analysis/blob/main/Dubai_Property_Pricing.pdf){target="_blank"}

 **Project Link:**  
[📄 Dubai Property Pricing Analysis (flex board)](https://rpubs.com/Chi_pubs/Dubai_Property_Prices){target="_blank"}




## Project 2

### Unemployment Disparity Among Gender and Race  
This project analyzes unemployment patterns in the United States across gender and racial groups. Using demographic employment data, I conducted exploratory analysis to compare unemployment rates, highlight inequalities, and identify population groups most affected. The project demonstrates the use of descriptive statistics, visualization, and comparative analysis to uncover social and economic disparities within the labor market.

🔗 **Project Link:**  
[📄 Unemployment Disparity Analysis (Notebook)](https://github.com/MercyOgbede-chi/Exploratory-Analysis/blob/main/Unemployment%20Disparity%20Among%20Gender%20and%20Race.ipynb){target="_blank"}
